language: haskell

notifications:
  email: false

before_install:
  - export PATH=/opt/ghc/7.10.3/bin:/opt/cabal/1.24/bin:$PATH

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.3
      - cabal-install-1.24

os:
  - linux
